// Self-contained mobile status page for Brett. Served directly from this
// backend at GET /dashboard so the page and GET /dashboard/summary share
// the same origin -- no cross-origin request headers are needed. Brett can
// bookmark this URL or add it to his phone's home screen.

export const DASHBOARD_HTML = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
<title>Car &amp; Solar Status</title>
<style>
  :root { color-scheme: dark; }
    * { box-sizing: border-box; }
      body {
          margin: 0;
              font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
                  background: #0b0f14;
                      color: #eef2f6;
                          min-height: 100vh;
                              display: flex;
                                  flex-direction: column;
                                      align-items: center;
                                          padding: 24px 16px 40px;
                                            }
                                              h1 {
                                                  font-size: 15px;
                                                      font-weight: 600;
                                                          color: #9aa7b4;
                                                              margin: 0 0 20px;
                                                                  text-transform: uppercase;
                                                                      letter-spacing: 0.08em;
                                                                        }
                                                                          .cards {
                                                                              width: 100%;
                                                                                  max-width: 420px;
                                                                                      display: flex;
                                                                                          flex-direction: column;
                                                                                              gap: 14px;
                                                                                                }
                                                                                                  .card {
                                                                                                      background: #151b23;
                                                                                                          border-radius: 18px;
                                                                                                              padding: 20px;
                                                                                                                  display: flex;
                                                                                                                      align-items: center;
                                                                                                                          gap: 16px;
                                                                                                                              border: 1px solid #232c37;
                                                                                                                                }
                                                                                                                                  .icon {
                                                                                                                                      font-size: 30px;
                                                                                                                                          width: 52px;
                                                                                                                                              height: 52px;
                                                                                                                                                  display: flex;
                                                                                                                                                      align-items: center;
                                                                                                                                                          justify-content: center;
                                                                                                                                                              border-radius: 14px;
                                                                                                                                                                  background: #1d2733;
                                                                                                                                                                      flex-shrink: 0;
                                                                                                                                                                        }
                                                                                                                                                                          .info { flex: 1; min-width: 0; }
                                                                                                                                                                            .label {
                                                                                                                                                                                font-size: 12px;
                                                                                                                                                                                    color: #7f8c99;
                                                                                                                                                                                        text-transform: uppercase;
                                                                                                                                                                                            letter-spacing: 0.06em;
                                                                                                                                                                                                margin-bottom: 2px;
                                                                                                                                                                                                  }
                                                                                                                                                                                                    .value { font-size: 21px; font-weight: 700; }
                                                                                                                                                                                                      .sub { font-size: 13px; color: #9aa7b4; margin-top: 2px; }
                                                                                                                                                                                                        .charging .icon { background: #16331f; }
                                                                                                                                                                                                          .charging .value { color: #4ade80; }
                                                                                                                                                                                                            .idle .value { color: #eef2f6; }
                                                                                                                                                                                                              .warn .value { color: #f3a13f; }
                                                                                                                                                                                                                .updated { margin-top: 22px; font-size: 12px; color: #5c6774; text-align: center; }
                                                                                                                                                                                                                  .dot {
                                                                                                                                                                                                                      display: inline-block;
                                                                                                                                                                                                                          width: 8px;
                                                                                                                                                                                                                              height: 8px;
                                                                                                                                                                                                                                  border-radius: 50%;
                                                                                                                                                                                                                                      background: #4ade80;
                                                                                                                                                                                                                                          margin-right: 6px;
                                                                                                                                                                                                                                              vertical-align: middle;
                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                  .error-banner {
                                                                                                                                                                                                                                                      width: 100%;
                                                                                                                                                                                                                                                          max-width: 420px;
                                                                                                                                                                                                                                                              background: #331a1a;
                                                                                                                                                                                                                                                                  border: 1px solid #5a2b2b;
                                                                                                                                                                                                                                                                      color: #f3a13f;
                                                                                                                                                                                                                                                                          padding: 12px 16px;
                                                                                                                                                                                                                                                                              border-radius: 12px;
                                                                                                                                                                                                                                                                                  font-size: 13px;
                                                                                                                                                                                                                                                                                      margin-bottom: 14px;
                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                        </style>
                                                                                                                                                                                                                                                                                        </head>
                                                                                                                                                                                                                                                                                        <body>
                                                                                                                                                                                                                                                                                          <h1>Home &amp; Car Status</h1>
                                                                                                                                                                                                                                                                                            <div id="errorBanner"></div>
                                                                                                                                                                                                                                                                                              <div class="cards" id="cards">
                                                                                                                                                                                                                                                                                                  <div class="card idle">
                                                                                                                                                                                                                                                                                                        <div class="icon">&#128663;</div>
                                                                                                                                                                                                                                                                                                              <div class="info">
                                                                                                                                                                                                                                                                                                                      <div class="label">Car</div>
                                                                                                                                                                                                                                                                                                                              <div class="value">Loading&hellip;</div>
                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                            <div class="updated" id="updated"></div>
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                            <script>
                                                                                                                                                                                                                                                                                                                                            function fmtPercent(n) {
                                                                                                                                                                                                                                                                                                                                              return (n === null || n === undefined) ? "--" : Math.round(n) + "%";
                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                              function fmtWatts(n) {
                                                                                                                                                                                                                                                                                                                                                if (n === null || n === undefined) return "--";
                                                                                                                                                                                                                                                                                                                                                  if (Math.abs(n) >= 1000) return (n / 1000).toFixed(1) + " kW";
                                                                                                                                                                                                                                                                                                                                                    return Math.round(n) + " W";
                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                    function render(data) {
                                                                                                                                                                                                                                                                                                                                                      var cards = document.getElementById("cards");
                                                                                                                                                                                                                                                                                                                                                        var errorBanner = document.getElementById("errorBanner");
                                                                                                                                                                                                                                                                                                                                                          var updated = document.getElementById("updated");
                                                                                                                                                                                                                                                                                                                                                            cards.innerHTML = "";
                                                                                                                                                                                                                                                                                                                                                              errorBanner.innerHTML = "";
                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                var v = data.vehicle;
                                                                                                                                                                                                                                                                                                                                                                  var isCharging = v && v.charging_state === "Charging";
                                                                                                                                                                                                                                                                                                                                                                    var carCard = document.createElement("div");
                                                                                                                                                                                                                                                                                                                                                                      carCard.className = "card " + (isCharging ? "charging" : "idle");
                                                                                                                                                                                                                                                                                                                                                                        if (v) {
                                                                                                                                                                                                                                                                                                                                                                            carCard.innerHTML =
                                                                                                                                                                                                                                                                                                                                                                                  '<div class="icon">&#128663;</div>' +
                                                                                                                                                                                                                                                                                                                                                                                        '<div class="info">' +
                                                                                                                                                                                                                                                                                                                                                                                              '<div class="label">Car</div>' +
                                                                                                                                                                                                                                                                                                                                                                                                    '<div class="value">' + (isCharging ? "Charging" : (v.plugged_in ? "Plugged in" : "Not plugged in")) + '</div>' +
                                                                                                                                                                                                                                                                                                                                                                                                          '<div class="sub">' + fmtPercent(v.state_of_charge) + ' battery' +
                                                                                                                                                                                                                                                                                                                                                                                                                (isCharging ? ' &middot; ' + Math.round(v.charging_current) + 'A' : '') + '</div>' +
                                                                                                                                                                                                                                                                                                                                                                                                                      '</div>';
                                                                                                                                                                                                                                                                                                                                                                                                                        } else {
                                                                                                                                                                                                                                                                                                                                                                                                                            carCard.className = "card warn";
                                                                                                                                                                                                                                                                                                                                                                                                                                carCard.innerHTML =
                                                                                                                                                                                                                                                                                                                                                                                                                                      '<div class="icon">&#128663;</div>' +
                                                                                                                                                                                                                                                                                                                                                                                                                                            '<div class="info">' +
                                                                                                                                                                                                                                                                                                                                                                                                                                                  '<div class="label">Car</div>' +
                                                                                                                                                                                                                                                                                                                                                                                                                                                        '<div class="value">Unavailable</div>' +
                                                                                                                                                                                                                                                                                                                                                                                                                                                              '<div class="sub">' + (data.vehicleError || "Could not reach the car") + '</div>' +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    '</div>';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        cards.appendChild(carCard);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          var solarCard = document.createElement("div");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            var s = data.solar;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if (s) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  solarCard.className = "card idle";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      solarCard.innerHTML =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            '<div class="icon">&#9728;</div>' +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  '<div class="info">' +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        '<div class="label">Solar</div>' +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              '<div class="value">' + fmtWatts(s.reading.solarProductionW) + '</div>' +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    '<div class="sub">Home using ' + fmtWatts(s.reading.homeLoadW) + '</div>' +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          '</div>';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                solarCard.className = "card warn";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    solarCard.innerHTML =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          '<div class="icon">&#9728;</div>' +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                '<div class="info">' +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      '<div class="label">Solar</div>' +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            '<div class="value">Not connected yet</div>' +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  '<div class="sub">Waiting on Sungrow setup</div>' +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        '</div>';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            cards.appendChild(solarCard);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if (s) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  var battCard = document.createElement("div");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      battCard.className = "card idle";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          var battState = s.reading.batteryPowerW === null ? "Battery power unknown" : (s.reading.batteryPowerW > 0 ? "Charging" : (s.reading.batteryPowerW < 0 ? "Discharging" : "Idle"));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              battCard.innerHTML =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    '<div class="icon">&#128267;</div>' +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          '<div class="info">' +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                '<div class="label">Home battery</div>' +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      '<div class="value">' + fmtPercent(s.reading.batterySocPercent) + '</div>' +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            '<div class="sub">' + battState + (s.reading.batteryPowerW === null ? '' : ' &middot; ' + fmtWatts(Math.abs(s.reading.batteryPowerW))) + '</div>' +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  '</div>';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      cards.appendChild(battCard);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          var decisionCard = document.createElement("div");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              decisionCard.className = "card idle";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  decisionCard.innerHTML =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        '<div class="icon">&#129504;</div>' +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              '<div class="info">' +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    '<div class="label">Latest decision</div>' +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          '<div class="value" style="font-size:16px;">' + s.decision.reason + '</div>' +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                '</div>';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    cards.appendChild(decisionCard);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        var now = new Date();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          updated.innerHTML = '<span class="dot"></span>Updated ' + now.toLocaleTimeString();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          function refresh() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fetch("/dashboard/summary", { cache: "no-store" })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .then(function (res) { return res.json(); })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    .then(render)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .catch(function () {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              document.getElementById("errorBanner").innerHTML =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      '<div class="error-banner">Could not reach the server. Retrying shortly.</div>';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          refresh();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          setInterval(refresh, 30000);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </script>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </body>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </html>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          `;
